name: thinkmay

include:
  # - path: ./compose/supabase.yaml
  # - path: ./compose/monitoring.yaml
  # - path: ./compose/kafka.yaml
  - path: ./compose/rybbit.yaml
  - path: ./compose/frontend.yaml

services:
  gateway:
    container_name: gateway
    build:
      context: ./gateway/proxy
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volumes/gateway/config.yaml:/etc/gateway/config.yaml:ro
      - ./volumes/gateway/pb_data:/var/lib/gateway/certs
    networks:
      - shared

networks:
  shared:
    name: thinkmay