name: thinkmay

include:
  - path: ./compose/supabase.yaml
  - path: ./compose/monitoring.yaml
  - path: ./compose/kafka.yaml
  - path: ./compose/rybbit.yaml

services:
  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./gateway/config.yaml:/etc/gateway/config.yaml:ro
      - ./volumes/gateway/certs:/var/lib/gateway/certs
    environment:
      CONFIG_PATH: /etc/gateway/config.yaml
    networks:
      - shared

  website:
    container_name: thinkmay-website
    build:
      context: ./website
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./website/.env
    networks:
      - shared

networks:
  shared:
    name: thinkmay