services:
  website:
    container_name: website
    build:
      context: ../website
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ../website/.env
    networks:
      - shared

  9router:
    image: pigeatgarlic/9router:latest
    container_name: 9router
    restart: unless-stopped
    environment:
      DATA_DIR: /app/data
      NEXT_TELEMETRY_DISABLED: "1"
    volumes:
      - ../9router:/app/data
    networks:
      - shared