services:
  fe:
    image: pigeatgarlic/fe:latest
    restart: unless-stopped
    env_file:
      - ../.env
  globalproxy:
    image: pigeatgarlic/global-proxy:latest
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ../assets/pb_data/.autocert_cache:/app/pb_data/.autocert_cache
    command:
      - '-dom'
      - 'official.thinkmay.net'
      - '-dom'
      - 'fe.thinkmay.net'
      - '-dom'
      - 'www.thinkmay.net'
      - '-dom'
      - 'thinkmay.net'
      - '-feport'
      - '443'
  9router:
    image: pigeatgarlic/9router:latest
    container_name: 9router
    restart: unless-stopped
    network_mode: host
    environment:
      DATA_DIR: /app/data
      PORT: 20128
      HOSTNAME: 10.30.30.35
      NEXT_TELEMETRY_DISABLED: "1"
      # DEBUG: "true"
    volumes:
      - ../9router:/app/data