

-- ACCOUNT SESSION
drop table if exists public.account_session;
create table public.account_session (
  id            bigint generated by default as identity primary key,

  account_id    uuid references auth.users not null,

  start_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  end_at     timestamp with time zone
);
comment on table public.account_session is 'Individual messages sent by each user.';

-- ACCOUNT MAIL
drop table if exists public.account_mail;
create type public.account_mail_type as enum ('START_APP');
create table public.account_mail (
  id            bigint generated by default as identity primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,

  from_id       uuid references auth.users not null,
  to_id         uuid references auth.users not null,

  message_type  account_mail_type not null,
  message       jsonb
);
comment on table public.account_mail is 'Individual messages sent from and to accounts.';



-- USER PROFILE
drop table if exists public.user_profile;
create table public.user_profile (
  id          bigint primary key not null, 
  account_id  uuid references auth.users not null,

  username    text,
  fullname    text,

  email       text,
  phone       text,

  metadata    jsonb
);
comment on table  public.user_profile                    is 'Profile data for each user.';
comment on column public.user_profile.id                 is 'References the internal Supabase Auth user.';

-- ROLE
create type public.role_type as enum ('ADMIN','USER','WORKER');
drop table if exists public.role;
create table public.role (
  id            bigint generated by default as identity primary key,

  role          role_type not null,
  metadata      jsonb
);
-- GLOBAL MAIL
create type public.global_mail_type as enum ('NEW_VERSION');
drop table if exists public.global_mail;
create table public.global_mail (
  id            bigint generated by default as identity primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,

  recv_role     role_type not null default 'USER',

  message_type  global_mail_type not null,
  message       jsonb
);

-- USER ROLE (MANY TO MANY)
drop table if exists public.user_role;
create table public.user_role (
  id            bigint generated by default as identity primary key,

  account_id    uuid   not null references auth.users,
  role_id       bigint not null references public.role
);

-- REGIONAL PROXY
drop table if exists public.regional_proxy;
create table public.regional_proxy (
  id            bigint generated by default as identity primary key,

  ip            text not null,

  region        text,
  metadata      jsonb
);
comment on table public.regional_proxy   is 'Regional proxy';

-- WORKER PROFILE
drop table if exists public.worker_profile;
create table public.worker_profile (
  id            bigint generated by default as identity primary key,

  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,

  account_id    uuid   references auth.users            not null,
  proxy_id      bigint references public.regional_proxy not null,

  active        boolean default true,
  last_update   timestamp with time zone default timezone('utc'::text, now()) not null,

  metadata      jsonb
);
comment on table  public.worker_profile              is 'Information of worker';
comment on column public.worker_profile.account_id   is 'public.auth column reference by account ';


-- WORKER METRIC
drop table if exists public.worker_metric;
create table public.worker_metric (
  id            bigint generated by default as identity primary key,

  worker_id     bigint not null references public.worker_profile,

  get_at        timestamp with time zone default timezone('utc'::text, now()) not null,
  val           jsonb not null
);
comment on table public.worker_metric is 'Worker metric reported by workers';


-- WORKER OWNERSHIP
create type public.ownership_type as enum ('OWNER','BORROWER','WATCHER');
drop table if exists public.worker_ownership;
create table public.worker_ownership (
  id            bigint generated by default as identity primary key,

  worker_id     bigint not null references public.worker_profile,
  user_id       bigint not null references public.user_profile,

  created_at    timestamp with time zone default timezone('utc'::text, now()) not null,

  o_type        ownership_type,
  metadata      jsonb
);
comment on table public.worker_ownership is 'Ownership orchestra accessability between specific worker and user';


-- SESSION MAIL
create type public.session_mail_type as enum ('SDP', 'ICE', 'START', 'END', 'PREFLIGHT');
create table public.session_mail (
  id            bigint generated by default as identity primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,

  from_id       bigint references public.account_session not null,
  to_id         bigint references public.account_session not null,

  message_type  session_mail_type not null,
  message       jsonb
);













-- APPLICATION IMAGE
drop table if exists public.application_image;
create table public.application_image (
  id               bigint generated by default as identity primary key,
  worker_id        bigint references public.worker_profile not null, 

  inserted_at      timestamp with time zone default timezone('utc'::text, now()) not null,
  deactivated_at   timestamp with time zone default timezone('utc'::text, now()) not null,

  name             text not null,
  path             text not null,
  args             jsonb,
  metadata         jsonb
);
-- WORKER APPLICATION
drop table if exists public.worker_application;
create table public.worker_application (
  id               bigint generated by default as identity primary key,

  session_id       bigint references public.account_session not null,
  app              bigint references public.application_image not null,

  metadata         jsonb
);
-- USER APPLICATION
drop table if exists public.user_application;
create table public.user_application (
  id            bigint generated by default as identity primary key,

  session_id         bigint references public.account_session,
  worker_app         bigint references public.worker_application,

  metadata         jsonb
);