---
name: CI-linux

on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  github_env:
    name: GitHub Env Debug
    runs-on: ubuntu-latest

    steps:
      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

  build_qemu_24:
    name: Qemu 24
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          mkdir -p artifacts
          docker build . -t qemu24 -f Dockerfile.qemu24 && docker run -v ./artifacts:/mnt/host qemu24
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qemu24-linux
          path: artifacts/prefix
  build_qemu_22:
    name: Qemu 22
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          mkdir -p artifacts
          docker build . -t qemu22 -f Dockerfile.qemu22 && docker run -v ./artifacts:/mnt/host qemu22
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qemu22-linux
          path: artifacts/prefix

  build_proxy:
    name: Proxy Linux
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: build-srt
        run: |
          git clone https://github.com/Haivision/srt
          cd srt

          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install tclsh pkg-config cmake libssl-dev build-essential
          ./configure && make
          sudo make install

      - name: build
        run: |
          cd ./worker/proxy/
          go mod download
          GOEXPERIMENT=greenteagc go build -o proxy  ./cmd/
      - name: copy binary
        run: |
          mkdir -p artifacts
          cp ./worker/proxy/proxy ./artifacts/proxy
          mkdir ./artifacts/srt
          cp /usr/local/lib/libsrt* ./artifacts/srt


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proxy-linux
          path: artifacts/ 

  build_daemon:
    name: Daemon Linux
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: build
        run: |
          sudo apt install -y libevdev-dev
          cd ./worker/daemon
          go mod download
          GOEXPERIMENT=greenteagc go build -o daemon ./cmd/
          GOEXPERIMENT=greenteagc go build -o pb     ./cmd/pocketbase/


      - name: copy binary
        run: |
          mkdir -p artifacts
          cp ./worker/daemon/daemon ./artifacts/daemon
          cp ./worker/daemon/pb ./artifacts/pb


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: daemon-linux
          path: artifacts/ 

  build_package: 
    name: Package Linux
    runs-on: ubuntu-latest
    needs: [build_daemon,build_proxy,build_qemu_22,build_qemu_24]
    steps:
      - uses: actions/download-artifact@v4
        name: download daemon
        with:
          name: daemon-linux
          path: daemon
      - uses: actions/download-artifact@v4
        name: download proxy
        with:
          name: proxy-linux
          path: proxy
      - uses: actions/download-artifact@v4
        name: download qemu
        with:
          name: qemu24-linux
          path: qemu24
      - uses: actions/download-artifact@v4
        name: download qemu
        with:
          name: qemu22-linux
          path: qemu22

      - name: build
        run: |
          git clone https://github.com/thinkonmay/assets -b ubuntu

          sudo apt install -y zip
          mkdir -p artifacts
          # mkdir -p assets/qemu

          cp daemon/daemon ./assets
          cp daemon/pb ./assets
          cp proxy/proxy ./assets
          cp -r qemu24/* ./assets/qemu24
          cp -r qemu22/* ./assets/qemu22
          cp -r proxy/srt ./assets/srt
          chmod 777 -R ./assets
          zip -r artifacts/linux.zip ./assets


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: msi-linux
          path: artifacts
  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: [build_package]

    steps:
      - uses: actions/download-artifact@v4
        name: download msi
        with:
          name: msi-linux
          path: artifacts
      - name: upload
        shell: bash
        run: >-
          curl https://saigon2.thinkmay.net/api/collections/binaries/records 
          -H "Content-Type: multipart/form-data" 
          --form "name=thinkmay_binary" 
          --form "file=@./artifacts/linux.zip"  
          --progress-bar 
